//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ged_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public file()
        {
            this.versions = new HashSet<version>();
        }
    
        public int idFile { get; set; }
        public int idUser { get; set; }
        public int idDirectory { get; set; }
        public Nullable<int> Use_idUser { get; set; }
        public string Name { get; set; }
        public System.DateTime dateCreationF { get; set; }
        public string format { get; set; }
        public short isLockedF { get; set; }
        public string urlF { get; set; }
        public short isDeletedF { get; set; }
        public string descriptionF { get; set; }
        public Nullable<short> IsArchiveF { get; set; }
        public string ArchiveNameF { get; set; }
        public Nullable<System.DateTime> ArchiveDateF { get; set; }
    
        public virtual directory directory { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<version> versions { get; set; }
    }
}
