//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ged_app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_gedEntities : DbContext
    {
        public db_gedEntities()
            : base("name=db_gedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<directory> directories { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<ownerinformation> ownerinformations { get; set; }
        public virtual DbSet<privilege> privileges { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usergroup> usergroups { get; set; }
        public virtual DbSet<version> versions { get; set; }
    }
}
