//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ged_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ownerinformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ownerinformation()
        {
            this.directories = new HashSet<directory>();
        }
    
        public int idOwner { get; set; }
        public string ownerName { get; set; }
        public string interlocutor { get; set; }
        public string address { get; set; }
        public string descriptionO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<directory> directories { get; set; }
    }
}
