//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ged_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class version
    {
        public int idVersion { get; set; }
        public int idFile { get; set; }
        public string descriptionV { get; set; }
        public System.DateTime dateCreationV { get; set; }
        public string VersionName { get; set; }
    
        public virtual file file { get; set; }
    }
}
